USE [master]
GO

/****** Object:  Database [NorthWindAzureForInserts]    Script Date: 9/13/2019 5:32:43 AM ******/
CREATE DATABASE [NorthWindAzureForInserts]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NorthWindAzureForInserts', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NorthWindAzureForInserts.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NorthWindAzureForInserts_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\NorthWindAzureForInserts_log.ldf' , SIZE = 2112KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NorthWindAzureForInserts] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NorthWindAzureForInserts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ARITHABORT OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET RECOVERY FULL 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET  MULTI_USER 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NorthWindAzureForInserts] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NorthWindAzureForInserts] SET  READ_WRITE 
GO


